import Head from 'next/head';
import React from 'react';
import Layout from '@/components/Layout';
import CreateKnife from "@/components/CreateKnife";

const CreateKnifePage = () => {
    return (
        <>
        <Head>
        <title>Crear Cuchillo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <CreateKnife/>
        </Layout>
        </>
        
    ) 
}

export default CreateKnifePage