import Head from 'next/head';
import React, { useState } from 'react';
import Layout from '@/components/Layout';
import Login from "@/components/Login";

const LoginPage = () => {

  const [token, setToken] = useState(null);

  return (
    <>
    <Head>
      <title>Iniciar Sesion</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Login setToken={setToken} />;
    </Layout>
    </>
  ) 
    
}

export default LoginPage;
