import Head from 'next/head';
import React from 'react';
import Layout from '@/components/Layout';
import RegisterUsersComponent from "@/components/RegisterUsers";

const RegisterUsersPage = () => {
  return (
    <>
     <Head>
        <title>Infinito JG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Layout>
      <RegisterUsersComponent />;
    </Layout>
    </>
  ) 
}

export default RegisterUsersPage;
