import Head from 'next/head';
import Layout from '@/components/Layout';
import { Navbar } from 'react-bootstrap';


export default function Home() {

  return (
    <>
      <Head>
        <title>Infinito JG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
         <Navbar/>
         <img src="/Anvil.webp" alt="yunke" className="success"/>
      </Layout>

      <main>

      </main>
    </>
  )
}
